const express = require('express')
const router = express.Router()
const Stripe = require('../helpers/stripe.helper')

module.exports = router

router.post('/stripe/pay', Stripe.pay)

router.get('/stripe/invoices', Stripe.getInvoices)
router.get('/stripe/invoices/:id', Stripe.getInvoice)
router.get('/stripe/products', Stripe.getProducts)
router.get('/stripe/products/:id', Stripe.getProduct)
router.get('/stripe/products/:id/skus', Stripe.getProductSKUs)
router.get('/stripe/skus', Stripe.getSKUs)
router.get('/stripe/skus/:id', Stripe.getSKU)
router.get('/stripe/plans', Stripe.getPlans)
router.get('/stripe/plans/:id', Stripe.getPlan)
router.get('/stripe/refunds', Stripe.getRefunds)
router.get('/stripe/refunds/:id', Stripe.getRefund)
router.get('/stripe/subscriptions', Stripe.getSubsriptions)
router.get('/stripe/subscriptions/:id', Stripe.getSubsription)
router.get('/stripe/charges', Stripe.getCharges)
router.get('/stripe/charges/:id', Stripe.getCharge)
router.get('/stripe/customers', Stripe.getCustomers)
router.get('/stripe/customers/:id', Stripe.getCustomerById)
router.get('/stripe/customers/email/:email', Stripe.getCustomerByEmail)
router.get('/stripe/customers/:id/sources', Stripe.getCustomerCards)
router.get('/stripe/setup_intents/:id', Stripe.getSetupIntent)
router.get('/stripe/setup_intents', Stripe.getSetupIntents)
router.get('/stripe/payment_intents/:id', Stripe.getPaymentIntent)
router.get('/stripe/payment_intents', Stripe.getPaymentIntents)

router.patch('/stripe/plans/:id', Stripe.updatePlan)
router.patch('/stripe/customers/:id/set-default-card', Stripe.setDefaultSource)
router.patch('/stripe/setup_intents/:id', Stripe.updateSetupIntent)
router.patch('/stripe/payment_intents/:id', Stripe.updatePaymentIntent)

router.post('/stripe/charges', Stripe.$createCharge)
router.post('/stripe/products', Stripe.createProduct)
router.post('/stripe/skus', Stripe.createSKU)
router.post('/stripe/plans', Stripe.createPlan)
router.post('/stripe/refunds', Stripe.createRefund)
router.post('/stripe/subscriptions', Stripe.createSubscription)
router.post('/stripe/customers/:id/sources', Stripe.createCustomerSource)
router.post('/stripe/invoices/:id/pay', Stripe.payInvoice)
router.post('/stripe/setup_intents', Stripe.createSetupIntent)
router.post('/stripe/setup_intents/:id/confirm', Stripe.confirmSetupIntent)
router.post('/stripe/setup_intents/:id/cancel', Stripe.cancelSetupIntent)
router.post('/stripe/payment_intents', Stripe.createPaymentIntent)
router.post('/stripe/payment_intents/:id/confirm', Stripe.confirmPaymentIntent)
router.post('/stripe/payment_intents/:id/capture', Stripe.capturePaymentIntent)
router.post('/stripe/payment_intents/:id/cancel', Stripe.cancelPaymentIntent)

router.delete('/stripe/products/:id', Stripe.deleteProduct)
router.delete('/stripe/sku/:id', Stripe.deleteSKU)
router.delete('/stripe/plans/:id', Stripe.deletePlan)
router.delete('/stripe/subscriptions/:id', Stripe.deleteSubscription)
router.delete('/stripe/customers/:id/sources/:fk', Stripe.deleteCustomerSource)
